### ISSUE TITLE
Taro$1.request is not a function

### ISSUE THREAD

**Issue by xhibbzzh** [fjc0k/taro-axios#19]
打包小程序之后 使用taro-axios报错
VM26977:1 Uncaught (in promise) thirdScriptError
Taro$1.request is not a function
TypeError: Taro$1.request is not a function

taro版本1.3.4
taro-axios版本 1.1.0

**Comment by fjc0k** [comment]
不看文档的吗？

![image](https://user-images.githubusercontent.com/13151189/78213401-1d87e700-74e5-11ea-9605-76ba17c6b208.png)
