### ISSUE TITLE
设置baseURL报错

### ISSUE THREAD

**Issue by ToPeas** [fjc0k/taro-axios#21]
无论是axios.create 形式
还是 axios.defaults 形式
设置baseURL报错，

版本1.1.0 

报错信息
Uncaught (in promise) thirdScriptError
Network Error
Error: Network Error

**Comment by fjc0k** [comment]
不设置 baseUrl 正常？

**Comment by WenMaoLin** [comment]
> 不设置baseUrl正常？

我也出现了这个问题，不设置baseURL正常

**Comment by ToPeas** [comment]
我重新在 config 里面手动加上baseURL就暂时能用了

**Comment by WenMaoLin** [comment]
> 我重新在 config 里面手动加上baseURL就暂时能用了

我目前也是暂时手动拼接上baseURL解决的

**Comment by WenMaoLin** [comment]
> 不设置 baseUrl 正常？

目前在 微信小程序上出现，h5 正常

**Comment by fjc0k** [comment]
你们是 Taro 几哦？1、2、3 中的几？
@ToPeas @WenMaoLin

**Comment by fjc0k** [comment]
我这儿是正常的，建议你们把代码发出来。

**Comment by WenMaoLin** [comment]
> 你们是 Taro 几哦？1、2、3 中的几？
> @ToPeas @WenMaoLin

taro 版本号 3.0.0 bate4. 
taro-axios 版本号 1.1.0

目前使用只有两个环境，在 h5 中没有发现异常，小程序则出现 Error: Network Error
似乎 baseURL 没有生效，暂时在 request.use 拦截器中 url 拼接了 baseURL 没有出现这个错误


```Javascript
const request = axios.create({
  baseURL: 'www.example.com/api'
})

// 中间省略拦截器

const get = request.get
const post = request.post

export {
  get,
  post
}

// 使用时
post('/news')

```

**Comment by fjc0k** [comment]
@WenMaoLin 也许你该给 baseUrl 加上协议名称，http:// 或者 https://

**Comment by fjc0k** [comment]
试试最新版本

**Comment by WenMaoLin** [comment]
> 试试最新版本

新版已解决👍
