### ISSUE TITLE
可以和axios-auth-refresh一起使用吗？

### ISSUE THREAD

**Issue by vinurs** [fjc0k/taro-axios#23]
我集成了axios-auth-refresh进来，确实在遇到401错误的时候重新走了认证的逻辑，不过貌似之前失败的请求在重新获取token以后并没有自动重新请求

**Comment by fjc0k** [comment]
这个我不清楚，建议你把同样的代码在 h5 用 axios 原版再试一次看看是不是同样。另外，不建议使用插件，自行封装就行。

**Comment by vinurs** [comment]
解决了，是可以使用的，axios-aut-refresh文档写得有点不清楚，参考https://github.com/Flyrell/axios-auth-refresh/issues/99
