### ISSUE TITLE
delete请求不能传data么？

### ISSUE THREAD

**Issue by catsayer-heat** [fjc0k/taro-axios#25]
**在小程序中，delete 请求操作传入data，会将传入的data去掉。**

这个是考虑到什么事情，所以才去掉的么？还是忘记了，因为我现在有个需要批量删除操作的delete请求，但是我发现传入的data数据并没有被小程序开发者工具发送，源码中看到下面一段代码：

```` javescript
const request = Taro.request({
        method: requestMethod as any,
        url: requestUrl,
        header: requestHeaders,
        // 请求数据只在 POST, PUT, PATCH 时设置
        data: requestMethod === 'POST' || requestMethod === 'PUT' || requestMethod === 'PATCH' ? requestData : '',
        // 响应的内容只能是 arraybuffer 或 text
        responseType: config.responseType === 'arraybuffer' ? 'arraybuffer' : 'text',
        // 响应数据的类型只能是 json 或 其他
        dataType: config.responseType === 'json' ? 'json' : config.responseType,
      })
````
data参数只有在post，put，patch时才进行设置

**Comment by fjc0k** [comment]
按照一些标准，delete 类似 get，传参只能通过查询字符串，因此你可以试试通过 params 传参。

**Comment by catsayer-heat** [comment]
> 按照一些标准，delete 类似 get，传参只能通过查询字符串，因此你可以试试通过 params 传参。

了解了，谢谢。但其实在实际的开发中，仍然会有一些后端会设置delete接口请求传递data。虽然我已经说服了我们公司的后端对接口请求方法进行更改，但不免一些后端仍会这样操作。

我的建议：建议是更改一下，因为axios的请求是可以通过delete请求传递data的。虽然最新版本的axios取消了axios.delete 方法对data的传递，但axios.request方法仍可以通过设置method为delete 传递data。而taro本身是一个多端的开发，如果不统一，那其仍需要对其进行兼容。

0.0 谢谢作者对代码的提供，我那些只是建议。当然，其实这些更加需要后端和前端配合达到代码上的统一标准。
