### ISSUE TITLE
库确定可以在Taro中使用？

### ISSUE THREAD

**Issue by wangxingkang** [fjc0k/taro-axios#3]

**Comment by fjc0k** [comment]
你那边不可以？

**Comment by wangxingkang** [comment]
集成了下 报错

**Comment by fjc0k** [comment]
什么错？

**Comment by wangxingkang** [comment]
我给复现一下

**Comment by wangxingkang** [comment]
thirdScriptError 
 sdk uncaught third Error 
 module "npm/taro-axios/lib/index.js" is not defined 
 Error: module "npm/taro-axios/lib/index.js" is not defined
    at require (http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7163)
    at http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:19725/appservice/utils/request.js:10:14
    at require (http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:19725/appservice/services/user.js:30:16
    at require (http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:19725/appservice/models/login.js:9:13
    at require (http://127.0.0.1:19725/appservice/__dev__/WAService.js:19:7304)

**Comment by wangxingkang** [comment]
"@tarojs/taro": "1.3.0-beta.6"

**Comment by fjc0k** [comment]
ok，我看看。

**Comment by fjc0k** [comment]
修复啦，安装新版试试。🥳

**Comment by wangxingkang** [comment]
赞
