### ISSUE TITLE
tarojs 1.3.4 下出错: TypeError: Cannot read property 'WEB' of undefined

### ISSUE THREAD

**Issue by Psli** [fjc0k/taro-axios#4]
环境
tarojs 1.3.4

出现错误: TypeError: Cannot read property 'WEB' of undefined

**Comment by Psli** [comment]
代码改为 
`Taro = require('@tarojs/taro-h5').default;`
修复
https://github.com/NervJS/taro/pull/3581

**Comment by fjc0k** [comment]
感谢反馈，请尝试新版本。
