### ISSUE TITLE
taro-axios@0.3.2 版本后会导致 taro-h5 中 treeshaking 不起作用

### ISSUE THREAD

**Issue by Psli** [fjc0k/taro-axios#5]
比如会引起 taro 未使用过 getSystemInfo 却仍然引用 mobile-detect第三方包，生成体积过大

与下面问题相关
#taro-h5 的 api 没有挂载到 export default Taro 上
https://github.com/NervJS/taro/pull/3581

https://github.com/NervJS/taro/issues/3700

**Comment by fjc0k** [comment]
试试最新版，记得给个反馈。😁

**Comment by Psli** [comment]
@fjc0k 已经修复，谢谢^_^
